server:
  servlet:
    context-path: /api

spring:
  application:
    name: api-financeiro
  jackson:
    time-zone: America/Sao_Paulo
  datasource:
    jpa:
      hibernate:
        ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect

endpoints:
  health:
    sensitive: false
    enabled: true

management:
  endpoints:
    enabled: false
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-components: ALWAYS
      show-details: NEVER

aplicacao:
  key: api-key
  token: aXRhw7o=