version: '3.7'
services:
  api-financeiro:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        aplicacao: api-financeiro
    ports:
      - "8581:8080"
    environment:
      TZ: "America/Sao_Paulo"
      SPRING_PROFILES_ACTIVE: dev
      XMS: 256m
      XMX: 256m
      versao: 1.0
    volumes:
      - "../logs:/logs"
